In [12]:
import sys
sys.path.extend(['/apps/ulstu/os/lab3/.venv/lib/python3.10/site-packages'])

In [11]:

import numpy as np
from tabulate import tabulate


In [203]:
A = np.array([[2, 1, 0],
              [2, 3, 1],
              [0, 0, 2]])

B = np.array([[1],
              [2],
              [3]])

C = np.array([[2, -1, 3]])

P = np.array([[3, 5, 7],
              [3, -4, 1],
              [-2, 5, 5]])

In [204]:
def matrix_minor(arr, i, j):
    return np.delete(np.delete(arr,i,axis=0), j, axis=1)


In [205]:
print('A` = P * A * P^-1')
print('Найдем обратную матрицу P^-1')
print('Шаг 1. Найдем определитель матрицы')

np.set_printoptions(precision=3, suppress=True, linewidth=255)

detP = int(np.linalg.det(P))

print(tabulate([[
    'det P = ',
    P[0][0], '*',
    str(matrix_minor(P, 0, 0)), '-',
    P[0][1], '*',
    str(matrix_minor(P, 0, 1)), '+',
    P[0][2], '*',
    str(matrix_minor(P, 0, 2)),
    '= 3×(−4×5−5×1)−5×(3×5−−2×1)+7×(3×5−−2×−4) =', detP
]], tablefmt="plain"))


if detP != 0:
    print('Определитель не равен 0, найдем обратную матрицу')
else:
    print('Определитель равен 0, обратная матрица P не существует')

A` = P * A * P^-1
Найдем обратную матрицу P^-1
Шаг 1. Найдем определитель матрицы
det P =  3  *  [[-4  1]   -  5  *  [[ 3  1]   +  7  *  [[ 3 -4]   = 3×(−4×5−5×1)−5×(3×5−−2×1)+7×(3×5−−2×−4) =  -111
                [ 5  5]]            [-2  5]]            [-2  5]]
Определитель не равен 0, найдем обратную матрицу


In [206]:
print('Шаг 2. Построим матрицу алгебраических дополнений')

Padd = np.zeros(P.shape)

for i in range(P.shape[0]):
    for j in range(P.shape[1]):
        M = matrix_minor(P, i, j)
        detM = np.linalg.det(M)
        idx = (-1) ** (i + j)
        Aij = idx * detM 
        
        Padd[i,j] = Aij
        
        print(tabulate([[
            f'A[{i+1}][{j+1}] = ',
            idx, '*',
            str(M), '=',
            Aij
        ]], tablefmt="plain"))



Шаг 2. Построим матрицу алгебраических дополнений
A[1][1] =  1  *  [[-4  1]   =  -25
                  [ 5  5]]
A[1][2] =  -1  *  [[ 3  1]   =  -17
                   [-2  5]]
A[1][3] =  1  *  [[ 3 -4]   =  7
                  [-2  5]]
A[2][1] =  -1  *  [[5 7]   =  10
                   [5 5]]
A[2][2] =  1  *  [[ 3  7]   =  29
                  [-2  5]]
A[2][3] =  -1  *  [[ 3  5]   =  -25
                   [-2  5]]
A[3][1] =  1  *  [[ 5  7]   =  33
                  [-4  1]]
A[3][2] =  -1  *  [[3 7]   =  18
                   [3 1]]
A[3][3] =  1  *  [[ 3  5]   =  -27
                  [ 3 -4]]


In [207]:
print('Матрица дополнений P')
print(Padd)


Матрица дополнений P
[[-25. -17.   7.]
 [ 10.  29. -25.]
 [ 33.  18. -27.]]


In [208]:
print('Шаг 3. Транспонируем матрицу алгебраических дополнений')
Ptr = np.transpose(Padd)
print(Ptr)


Шаг 3. Транспонируем матрицу алгебраических дополнений
[[-25.  10.  33.]
 [-17.  29.  18.]
 [  7. -25. -27.]]


In [209]:
print('Шаг 4. Находим обратную матрицу')

P1 = (1 / detP) * Ptr
print(tabulate([[
            f'P^-1 = 1 / {detP} * ',
            str(Ptr), '=',
            str(P1)
        ]], tablefmt="plain"))


Шаг 4. Находим обратную матрицу
P^-1 = 1 / -111 *  [[-25.  10.  33.]   =  [[ 0.225 -0.09  -0.297]
                    [-17.  29.  18.]       [ 0.153 -0.261 -0.162]
                    [  7. -25. -27.]]      [-0.063  0.225  0.243]]


In [210]:
print('Найдена обратная матрица P^-1')
print(P1)


Найдена обратная матрица P^-1
[[ 0.225 -0.09  -0.297]
 [ 0.153 -0.261 -0.162]
 [-0.063  0.225  0.243]]


In [211]:
print('Шаг 5. Проверим обратную матрицу через numpy.linalg.inv')
np.linalg.inv(P)

Шаг 5. Проверим обратную матрицу через numpy.linalg.inv


array([[ 0.225, -0.09 , -0.297],
       [ 0.153, -0.261, -0.162],
       [-0.063,  0.225,  0.243]])

In [212]:
print('Шаг 5. Проверим обратную матрицу через умножение')
print(np.dot(P, P1))

Шаг 5. Проверим обратную матрицу через умножение
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]


In [213]:
print('Вычисляем преобразование P * A * P^-1')

print('Шаг 1. Вычисляем P * A')

Mul = np.array([[f'{P[0,0]} * {A[0,0]} + {P[0,1]} * {A[1,0]} + {P[0,2]} * {A[2,0]},',
                 f'{P[0,0]} * {A[0,1]} + {P[0,1]} * {A[1,1]} + {P[0,2]} * {A[2,1]},',
                 f'{P[0,0]} * {A[0,2]} + {P[0,1]} * {A[1,2]} + {P[0,2]} * {A[2,2]}'],
                [f'{P[1,0]} * {A[0,0]} + {P[1,1]} * {A[1,0]} + {P[1,2]} * {A[2,0]},',
                 f'{P[1,0]} * {A[0,1]} + {P[1,1]} * {A[1,1]} + {P[1,2]} * {A[2,1]},',
                 f'{P[1,0]} * {A[0,2]} + {P[1,1]} * {A[1,2]} + {P[1,2]} * {A[2,2]}'],
                [f'{P[2,0]} * {A[0,0]} + {P[2,1]} * {A[1,0]} + {P[2,2]} * {A[2,0]},',
                 f'{P[2,0]} * {A[0,1]} + {P[2,1]} * {A[1,1]} + {P[2,2]} * {A[2,1]},',
                 f'{P[2,0]} * {A[0,2]} + {P[2,1]} * {A[1,2]} + {P[2,2]} * {A[2,2]}']])

PA = np.dot(P, A)
print(tabulate([[
            'P * A = ',
            str(P), '*',
            str(A), '=',
            str(Mul), '=',
            str(PA)
        ]], tablefmt="plain"))



Вычисляем преобразование P * A * P^-1
Шаг 1. Вычисляем P * A
P * A =  [[ 3  5  7]   *  [[2 1 0]   =  [['3 * 2 + 5 * 2 + 7 * 0,' '3 * 1 + 5 * 3 + 7 * 0,' '3 * 0 + 5 * 1 + 7 * 2']      =  [[16 18 19]
          [ 3 -4  1]       [2 3 1]       ['3 * 2 + -4 * 2 + 1 * 0,' '3 * 1 + -4 * 3 + 1 * 0,' '3 * 0 + -4 * 1 + 1 * 2']       [-2 -9 -2]
          [-2  5  5]]      [0 0 2]]      ['-2 * 2 + 5 * 2 + 5 * 0,' '-2 * 1 + 5 * 3 + 5 * 0,' '-2 * 0 + 5 * 1 + 5 * 2']]      [ 6 13 15]]


In [214]:
print('Шаг 2. Вычисляем P * A * P^-1')

Mul = np.array([[f'{PA[0,0]} * {P1[0,0]:.4f} + {PA[0,1]} * {P1[1,0]:.4f} + {PA[0,2]} * {P1[2,0]:.4f},',
                 f'{PA[0,0]} * {P1[0,1]:.4f} + {PA[0,1]} * {P1[1,1]:.4f} + {PA[0,2]} * {P1[2,1]:.4f},',
                 f'{PA[0,0]} * {P1[0,2]:.4f} + {PA[0,1]} * {P1[1,2]:.4f} + {PA[0,2]} * {P1[2,2]:.4f}'],
                [f'{PA[1,0]} * {P1[0,0]:.4f} + {PA[1,1]} * {P1[1,0]:.4f} + {PA[1,2]} * {P1[2,0]:.4f},',
                 f'{PA[1,0]} * {P1[0,1]:.4f} + {PA[1,1]} * {P1[1,1]:.4f} + {PA[1,2]} * {P1[2,1]:.4f},',
                 f'{PA[1,0]} * {P1[0,2]:.4f} + {PA[1,1]} * {P1[1,2]:.4f} + {PA[1,2]} * {P1[2,2]:.4f}'],
                [f'{PA[2,0]} * {P1[0,0]:.4f} + {PA[2,1]} * {P1[1,0]:.4f} + {PA[2,2]} * {P1[2,0]:.4f},',
                 f'{PA[2,0]} * {P1[0,1]:.4f} + {PA[2,1]} * {P1[1,1]:.4f} + {PA[2,2]} * {P1[2,1]:.4f},',
                 f'{PA[2,0]} * {P1[0,2]:.4f} + {PA[2,1]} * {P1[1,2]:.4f} + {PA[2,2]} * {P1[2,2]:.4f}']])

PAP = np.dot(PA, P1)
print(tabulate([[
            'P * A * P^-1 = ',
            str(PA), '*',
            str(P1), '=',
            str(Mul), '=',
            str(PAP)
        ]], tablefmt="plain"))


Шаг 2. Вычисляем P * A * P^-1
P * A * P^-1 =  [[16 18 19]   *  [[ 0.225 -0.09  -0.297]   =  [['16 * 0.2252 + 18 * 0.1532 + 19 * -0.0631,' '16 * -0.0901 + 18 * -0.2613 + 19 * 0.2252,' '16 * -0.2973 + 18 * -0.1622 + 19 * 0.2432']  =  [[ 5.162 -1.865 -3.054]
                 [-2 -9 -2]       [ 0.153 -0.261 -0.162]       ['-2 * 0.2252 + -9 * 0.1532 + -2 * -0.0631,' '-2 * -0.0901 + -9 * -0.2613 + -2 * 0.2252,' '-2 * -0.2973 + -9 * -0.1622 + -2 * 0.2432']      [-1.703  2.081  1.568]
                 [ 6 13 15]]      [-0.063  0.225  0.243]]      ['6 * 0.2252 + 13 * 0.1532 + 15 * -0.0631,' '6 * -0.0901 + 13 * -0.2613 + 15 * 0.2252,' '6 * -0.2973 + 13 * -0.1622 + 15 * 0.2432']]        [ 2.396 -0.559 -0.243]]


In [215]:
print('Проверяем np.linalg.multi_dot([P, A, P1])')
np.linalg.multi_dot([P, A, P1])

Проверяем np.linalg.multi_dot([P, A, P1])


array([[ 5.162, -1.865, -3.054],
       [-1.703,  2.081,  1.568],
       [ 2.396, -0.559, -0.243]])

In [216]:
print('Вычисляем преобразование B` = P * B')

Mul = np.array([[f'{P[0,0]} * {B[0,0]} + {P[0,1]} * {B[1,0]} + {P[0,2]} * {B[2,0]},'],
                [f'{P[1,0]} * {B[0,0]} + {P[1,1]} * {B[1,0]} + {P[1,2]} * {B[2,0]},'],
                [f'{P[2,0]} * {B[0,0]} + {P[2,1]} * {B[1,0]} + {P[2,2]} * {B[2,0]},']])

PB = np.dot(P, B)
print(tabulate([[
            'P * B = ',
            str(P), '*',
            str(B), '=',
            str(Mul), '=',
            str(PB)
        ]], tablefmt="plain"))


Вычисляем преобразование B` = P * B
P * B =  [[ 3  5  7]   *  [[1]   =  [['3 * 1 + 5 * 2 + 7 * 3,']    =  [[34]
          [ 3 -4  1]       [2]       ['3 * 1 + -4 * 2 + 1 * 3,']       [-2]
          [-2  5  5]]      [3]]      ['-2 * 1 + 5 * 2 + 5 * 3,']]      [23]]


In [217]:
print('Вычисляем преобразование C` = C * P1')

Mul = np.array([[f'{C[0,0]} * {P1[0,0]:.4f} + {C[0,1]} * {P1[1,0]:.4f} + {C[0,2]} * {P1[2,0]:.4f},',
                 f'{C[0,0]} * {P1[0,1]:.4f} + {C[0,1]} * {P1[1,1]:.4f} + {C[0,2]} * {P1[2,1]:.4f},',
                 f'{C[0,0]} * {P1[0,2]:.4f} + {C[0,1]} * {P1[1,2]:.4f} + {C[0,2]} * {P1[2,2]:.4f}']])

CP = np.dot(C, P1)
print(tabulate([[
            'C * P1 = ',
            str(C), '*',
            str(P1), '=',
            str(Mul), '=',
            str(CP)
        ]], tablefmt="plain"))



Вычисляем преобразование C` = C * P1
C * P1 =  [[ 2 -1  3]]  *  [[ 0.225 -0.09  -0.297]   =  [['2 * 0.2252 + -1 * 0.1532 + 3 * -0.0631,' '2 * -0.0901 + -1 * -0.2613 + 3 * 0.2252,' '2 * -0.2973 + -1 * -0.1622 + 3 * 0.2432']]  =  [[0.108 0.757 0.297]]
                            [ 0.153 -0.261 -0.162]
                            [-0.063  0.225  0.243]]


In [218]:
print('Ответ:')

print('P` = P * A * P^-1')
print(PAP)


Ответ:
P` = P * A * P^-1
[[ 5.162 -1.865 -3.054]
 [-1.703  2.081  1.568]
 [ 2.396 -0.559 -0.243]]


In [219]:
print('B` = P * B')
print(PB)


B` = P * B
[[34]
 [-2]
 [23]]


In [220]:
print('C` = C * P-1')
print(CP)


C` = C * P-1
[[0.108 0.757 0.297]]
